FROM registry.cn-beijing.aliyuncs.com/wfapp/centos:7.6.1810

RUN yum install -y lapack lapack-devel
 
# Install necessary build tools
RUN yum install -y gcc-c++ make 
RUN yum install -y swig3
RUN yum install -y java-1.8.0-openjdk java-1.8.0-openjdk-devel